# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Сбитнева Мария Алексеевна
- ЗПИЭ-20-2

| Задание | Сам_раб |
| ------  | ------ |
| Задание 1 | + |
| Задание 2 | + |
| Задание 3 | + |
| Задание 4 | + |
| Задание 5 | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы.

```python
import time

def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f'\nФункция была выполнена за {end_time - start_time:.4f} сек.')
        return result
    return wrapper

@timer_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```

### Результат
![Меню](https://github.com/segamega-drive/software_engineering/blob/ded93d1343abf51cb710fe11a2bfbecd604dfc5a/img/10.1.png)

## Выводы
В данном задании мы знакомимся с декораторами, в рамках условий узнали могут быть использованы для изменения поведения функций и конкретно для измерения времени её выполнения.
  
## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(filename):
    try:
        file = open(filename, 'r', encoding='utf-8-sig')
        content = file.read()
        if not content:
            raise Exception("Файл пустой")
        print(content)
    except Exception as e:
        print(str(e))


if __name__ == '__main__':
    read_file('empty.txt')
    read_file('nonempty.txt')
```

### Результат
![Меню](https://github.com/segamega-drive/software_engineering/blob/ded93d1343abf51cb710fe11a2bfbecd604dfc5a/img/10.2.png)

## Выводы
В данном задании мы познакомились с конструкцией try/except, которая используется для обработки исключений. В блок try помещается код, который может вызвать исключение, а в блок except — код, который будет выполнен, если исключение возникнет. Это позволяет избежать аварийного завершения программы.
  
## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def sum_two_numbers():
    try:
        num = float(input('Введите число:\n'))
        res = num + 2
        return res
    except ValueError:
        return 'Неподходящий тип данных. Ожидалось число.'

print(sum_two_numbers())
```

### Результат
![Меню](https://github.com/segamega-drive/software_engineering/blob/ded93d1343abf51cb710fe11a2bfbecd604dfc5a/img/10.3.png)

## Выводы
В данном задании мы используем блок try/except для обработки ошибки, которая может возникнуть при попытке преобразовать ввод пользователя в число. Если ввод не может быть преобразован в число, то вызывается исключение ValueError, которое перехватывается в блоке except и возвращается сообщением об ошибке.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
# Декоратор функций, который логирует результаты вызова функции
def my_decorator(func):
    def wrapper(name):
        func(name)  # Вызываем функцию с аргументом name
    # Возвращаем обёртку, которая будет вызываться вместо оригинальной функции    return wrapper


# Декоратор @my_decorator добавляет логирование к функции say_bye
@my_decoratordef say_hello(name):
    print('Добрый день,', name)


# Декоратор @my_decorator добавляет логирование к функции say_bye
@my_decoratordef say_bye(name):
    print('Доброй ночи,', name)


# Основная часть программы, которая вызывает функции
name = input('Введите своё имя: ')  # Запрашиваем имя пользователя
say_hello(name)  # Вызываем функцию say_hello с аргументом name
say_bye(name)  # Вызываем функцию say_bye с аргументом name
```

### Результат
![Меню](https://github.com/segamega-drive/software_engineering/blob/71815fcda4c89b13a5e1d2154cdca324d7346384/img/10.4.png)

## Выводы
В данном задании мы научились создавать и использовать собственные декораторы. Так, мы создаём декоратор my_decorator, который логирует результаты вызова функции. Затем определяем две функции, которые хотим логировать. Вызываем эти функции с именем пользователя, введенным вручную.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
### 

```python

```

### Результат
![Меню](https://github.com/segamega-drive/software_engineering/blob/5fa07419a16955c27bf309058ae95e5c8a8c280f/img/10.5.png)

## Выводы
В данном задании мы создали  исключение MyException, затем применили его в двух функциях. В первой функции мы вызываем исключение, если введенное пользователем число не положительно. Во второй функции мы вызываем исключение, если введенная пользователем строка содержит не только буквы. В обоих этих функциях мы используем блок try/except для обработки исключения, выводится сообщение об исключении. Если исключение не возникает, то выполнение функции продолжается.

## Общие выводы по теме
В данной теме мы ознакомились с декораторами, они могут расширять и изменять поведение вызываемых функций, методов или классов без постоянного изменения самого вызываемого объекта. Исключения позволяют управлять поведением программы при возникновении ошибок, они обрабатывают ошибки. Также научились создавать собственные декораторы и исключения.
